package net.minestom.server.storage.systems;

import java.nio.file.Files;
import java.nio.file.Paths;

import me.devtec.server.configs.Data;
import net.minestom.server.storage.StorageSystem;

/**
 * A {@link StorageSystem} which is local using OS files system
 * It does make use of the RocksDB library.
 * <p>
 * The location represents the path of the folder.
 * <p>
 * Warning: will create some log files in the location folder when opened, those are generated by RocksDB.
 */
public class FileStorageSystem implements StorageSystem {
	
    private Data data;

    @Override
    public boolean exists(String location) {
        return Files.isDirectory(Paths.get(location));
    }

	@Override
    public void open(String location) {
        data=new Data(location);
    }

    @Override
    public byte[] get(String key) {
    	return data.getAs(key, byte[].class);
    }

    @Override
    public void set(String key, byte[] data) {
        this.data.set(key, data);
    }

    @Override
    public void delete(String key) {
        this.data.remove(key);
    }

	@Override
	public void close() {
		data.save();
		data.clear();
	}

}
